DISEASE_DATABASE = [
    {
        "id": 0,
        "class_key": "Tomato_Early_blight",
        "crop_ar": "الطماطم",
        "crop_en": "Tomato",
        "disease_ar": "اللفحة المبكرة",
        "disease_en": "Early Blight",
        "pathogen": "Alternaria solani",
        "pathogen_type_ar": "فطر",
        "pathogen_type_en": "Fungus",
        "symptoms": "بقع بنية دائرية ذات حلقات متداخلة على الأوراق والثمار.",
        "recommendation": "إزالة الأجزاء المصابة، تقليل الرطوبة، تحسين التهوية، واستخدام برنامج مكافحة مناسب.",
        "source": "Atlas of Plant Diseases - Assiut University"
    },
    {
        "id": 1,
        "class_key": "Tomato_Late_blight",
        "crop_ar": "الطماطم / البطاطس",
        "crop_en": "Tomato / Potato",
        "disease_ar": "اللفحة المتأخرة",
        "disease_en": "Late Blight",
        "pathogen": "Phytophthora infestans",
        "pathogen_type_ar": "شبيه فطري",
        "pathogen_type_en": "Oomycete",
        "symptoms": "بقع مائية داكنة تنتشر بسرعة على الأوراق والسيقان والثمار.",
        "recommendation": "تقليل الرطوبة، إزالة الأجزاء المصابة، وتطبيق برنامج مكافحة وقائي.",
        "source": "Atlas of Plant Diseases - Assiut University"
    },
    {
        "id": 2,
        "class_key": "Tomato_Gray_mold",
        "crop_ar": "الطماطم / الفراولة / البصل",
        "crop_en": "Tomato / Strawberry / Onion",
        "disease_ar": "العفن الرمادي",
        "disease_en": "Gray Mold",
        "pathogen": "Botrytis cinerea",
        "pathogen_type_ar": "فطر",
        "pathogen_type_en": "Fungus",
        "symptoms": "نمو رمادي زغبي على الثمار أو الأنسجة المصابة خاصة مع الرطوبة العالية.",
        "recommendation": "تحسين التهوية، تقليل الرطوبة، إزالة الأنسجة المصابة، وتجنب تزاحم النباتات.",
        "source": "Atlas of Plant Diseases - Assiut University"
    },
    {
        "id": 3,
        "class_key": "Tomato_Bacterial_wilt",
        "crop_ar": "الطماطم / البطاطس",
        "crop_en": "Tomato / Potato",
        "disease_ar": "الذبول البكتيري",
        "disease_en": "Bacterial Wilt",
        "pathogen": "Ralstonia solanacearum",
        "pathogen_type_ar": "بكتيريا",
        "pathogen_type_en": "Bacteria",
        "symptoms": "ذبول مفاجئ للنبات مع بقاء الأوراق خضراء نسبيًا في البداية.",
        "recommendation": "استبعاد النباتات المصابة، تعقيم الأدوات، تحسين الصرف، وتجنب نقل التربة الملوثة.",
        "source": "Atlas of Plant Diseases - Assiut University"
    },
    {
        "id": 4,
        "class_key": "Tomato_Bacterial_spot",
        "crop_ar": "الطماطم",
        "crop_en": "Tomato",
        "disease_ar": "التبقع البكتيري",
        "disease_en": "Bacterial Spot",
        "pathogen": "Xanthomonas vesicatoria",
        "pathogen_type_ar": "بكتيريا",
        "pathogen_type_en": "Bacteria",
        "symptoms": "بقع صغيرة داكنة على الأوراق والثمار وقد تتحد مسببة تلفًا واسعًا.",
        "recommendation": "تجنب الرش العلوي، استخدام بذور سليمة، إزالة البقايا المصابة، وتطبيق مكافحة مناسبة.",
        "source": "Atlas of Plant Diseases - Assiut University"
    }
]
